### ISSUE TITLE
wrong images

### ISSUE THREAD

**Issue by Andyauk** [Constant-Development/cr-247extras#3]
this is in order the maker gives.
<a href="https://ibb.co/7jQJr3x"><img src="https://i.ibb.co/5GkWsQX/New-Project.png" alt="New-Project" border="0"></a>

**Comment by realSixGrams** [comment]
BlueSlushy Image has been updated, and same with the RainbowSlushy Item. Regarding the Yellow and Green Slushy, those will be updated once I am to find a proper Image.
