### ISSUE TITLE
errors 

### ISSUE THREAD

**Issue by Andyauk** [Constant-Development/cr-247extras#5]
red sticks to hand still

orange gives errors line 21 of client consumables
`gerServerEvent("QBCore:Server:SetMetaData", "thirst", QBCore.Functions.GetPlayerData().metadata["thirst"] + ConsumeablesSlushy[itemName])
`

with latest version

**Comment by Andyauk** [comment]
i noticed your missing ConsumeablesSlushy = { for orange

**Comment by realSixGrams** [comment]
Ahh, okok I notice what you're saying now. Yes, that is missing - My bad on that one.

**Comment by realSixGrams** [comment]
I've pushed the 'orangeslushy' being inside of the 'ConsumablesSlushy = {'
